# Generated by Django 2.0.2 on 2018-02-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
